name: "🎨 UI/UX Enhancement"
description: Suggest a UI/UX enhancement to make us look better.
title: "🎨 [UI/UX Enhancement] - <title>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: expected-behaviour
    attributes:
      label: "Expected UI"
      description: Please describe the UI you are expecting
      placeholder: Short and explicit description of your desired UI...
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: "Current UI"
      description: Please describe the current UI
      placeholder: What is the current UI behaviour?...
    validations:
      required: true
  - type: input
    id: figma-url
    attributes:
      label: "Figma Design if available"
      description: Please enter figma designs url, if available
      placeholder: Figma Link
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your enhancement.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: dapp-env
    attributes:
      label: "Dapp Env"
      description: What is the impacted DApp environment ?
      multiple: true
      options:
        - Prod (app.push.org)
        - Staging (staging.push.org)
        - Dev (dev.push.org)
    validations:
      required: true