name: Deploy PR previews
on:
  pull_request:
    types: [synchronize]
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and Build
        if: github.event.action != 'closed'
        run: |
          yarn install
          yarn build:pr:preview
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1.4.7
        with:
          source-dir: ./build/
